export const config={api:{bodyParser:{sizeLimit:'12mb'}},maxDuration:30};
function send(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));}
function outputText(p){if(p.output_text)return p.output_text;return(p.output||[]).flatMap(x=>x.content||[]).map(x=>x.text||'').join('');}
function parseJson(t){return JSON.parse(t.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''));}
export default async function handler(req,res){
  if(req.method!=='POST'){res.setHeader('Allow','POST');return send(res,405,{error:'Method not allowed'});} if(!process.env.OPENAI_API_KEY)return send(res,503,{error:'OPENAI_API_KEY missing'});
  const {reference_image,current_image,target,last_position}=req.body||{}; if(!reference_image||!current_image)return send(res,400,{error:'reference_image and current_image are required'});
  try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_VISION_MODEL||'gpt-5-mini',input:[{role:'user',content:[{type:'input_text',text:`Compare these two place photos for navigation confirmation. Target=${JSON.stringify(target||null)}, last_position=${JSON.stringify(last_position||null)}. Return JSON only: match_score 0-100, same_place boolean, confidence low|medium|high, instruction short Polish navigation hint, reason short Polish explanation, matched_features array, position_hint short Polish string. Do not identify people.`},{type:'input_image',image_url:reference_image,detail:'high'},{type:'input_image',image_url:current_image,detail:'high'}]}],max_output_tokens:500})}); if(!r.ok)return send(res,502,{error:`OpenAI vision failed: HTTP ${r.status}`}); return send(res,200,parseJson(outputText(await r.json())));}catch(e){return send(res,500,{error:e.message});}
}
